name: name
trigger: 
  branches:
    include:
      - master
pool:
  name: poolname
variables:
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
    displayName: dotnet test
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      arguments: '--configuration $(buildConfiguration)'
  - task: Docker@2
    inputs:
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
  - task: PowerShell@2
    displayName: run powershell